### ISSUE TITLE
migrate telemetry module

### ISSUE THREAD

**Issue by edublancas** [ploomber/core#1]
We'll start using the telemetry module in several projects so we need to migrate the [module](https://github.com/ploomber/ploomber/tree/master/src/ploomber/telemetry) to here. Note that the telemetry module also imports from the `ploomber.config` module so we have to move it as well.

- [x] migrate telemetry code to this repository
- [x] migrate tests (some tests check that ploomber calls the telemetry module, those should stay there, only move the ones that test core functionality, if in doubt, ask)
- [x] submit ploomber PR deleting the code, tests and using ploomber_core
- [x] add config files for mac and windows CI testing
- [ ] submit PR to soopervisor so it uses ploomber_core 

*Note:* ploomber and soopervisor PRs will fail since this isn't available on PyPI yet, once the PR here is working. I'll upload to PyPI so ploomber and soopervisor pass

**Comment by Wxl19980214** [comment]
First two tasks done.

**Comment by Wxl19980214** [comment]
What do you mean by this step:  add config files for mac and windows CI testing
Do you mean we need to add ploomber_core to setup requirement? Like its a new package and we will have to install it first in CI ?

**Comment by edublancas** [comment]
i mean testing the package on windows and mac, we are only testing on linux:

https://github.com/ploomber/core/tree/main/.github/workflows

**Comment by Wxl19980214** [comment]
ah you mean adding testing workflow for the new package. I see

**Comment by edublancas** [comment]
made a first release after merging #1, we can now start integrating this into ploomber and soopervisor:

```
pip install ploomber-core
```

**Comment by edublancas** [comment]
released ploomber-core 0.0.2 with your latest changes to support multiple keys, you can now work on the PRs for ploomber and soopervisor
