### ISSUE TITLE
imported without any action

### ISSUE THREAD

**Issue by idomic** [ploomber/core#34]
There are lots of users with just imported but not other actions:

![Screen Shot 2023-01-10 at 10 21 22 AM](https://user-images.githubusercontent.com/11596985/211590868-b2c2d2b3-c690-4ab6-8a95-5639e3b4f644.png)

Ref: https://app.posthog.com/person/441e337e-8714-408a-b645-b4e5f12c95b0#activeTab=events

**Comment by edublancas** [comment]
when we first added telemetry to some packages, we only added the imported event, so these might be users running old versions. I think we should keep a telemetry changelog so we can easily find out if a given version corresponds to one that has limited telemetry
