### ISSUE TITLE
parameterize posthog.project_api_key

### ISSUE THREAD

**Issue by idomic** [ploomber/core#4]
We need to make sure this is configurable so other modules can use their own key.

https://github.com/ploomber/core/blob/ce7ff27b14c662109de32364a1611655b5273725/src/ploomber_core/telemetry/telemetry.py#L53

**Comment by Wxl19980214** [comment]
So are u saying each project in ploomber correspond to one posthog project? For example, we shoulld have three now for soorgeon, ploomber and sooperviosr?

**Comment by idomic** [comment]
It's possible, we'll run some experiments, some of those will need a unique uuid.

**Comment by edublancas** [comment]
solved by #5
