### ISSUE TITLE
Discuss: Support modify_exceptions with TypeError

### ISSUE THREAD

**Issue by tonykploomber** [ploomber/core#41]
Context:
I am modifying our other project (jupysql) to support it's exception class (`ValueError` and `TypeError`) with custom error message. However, only `ValueError` can be applied with `modify_exceptions` decorator to wrap the exception case.

I propose to support `TypeError` as well, which is much more generic.

[Current implementation](https://github.com/ploomber/core/blob/main/src/ploomber_core/exceptions.py#L74) in `def modify_exceptions`:
```
...
        except ValueError as e:
...
```

Proposed implementation:
```
...
        except (ValueError, TypeError) as e:
...
```

**Comment by tonykploomber** [comment]
@edublancas Let me know what you think, since we need this change to unblock the https://github.com/ploomber/jupysql/issues/30

Meanwhile, I can think about how to add the [if statement](https://github.com/ploomber/jupysql/pull/106#issuecomment-1411367155) to avoid the duplicated community link in this PR as well...

**Comment by idomic** [comment]
@tonykploomber it's better to do this discussion over a PR since it's a small fix.
We should support both types and I think the if (which I mentioned yesterday is a good fix). Let me review it.

**Comment by idomic** [comment]
Also, you should add to the PRs closes: # issue number so we don't have to manually do it.

**Comment by idomic** [comment]
@tonykploomber also, I didn't notice it but you forgot to add changelog entries. I've added it so we can release but make sure it's part of the PR next time.

**Comment by tonykploomber** [comment]
Thanks Ido!
