### ISSUE TITLE
logging future warnings

### ISSUE THREAD

**Issue by edublancas** [ploomber/core#50]
whenever we have to change the API, we display a FutureWarning to users so they have a chance to update their code. However, we don't know the proportion of them that already switched.

It'd be better to log these events, so we know when users need more time to switch because we want to ship new features as fast as possible without compromising stability.

We can add a `telemetry.deprecation_warning` method that uses `warnings.warn` (with FutureWarning) and captures the event.

**Comment by tonykploomber** [comment]
Do you mean every time we show the future warnings, meanwhile we will log the event to PostHog?

**Comment by edublancas** [comment]
a function that will show a FutureWarning, but also log the event to posthog

**Comment by edublancas** [comment]
We created the `@deprecated.*`  decorators when we were mostly working in sklearn-evaluation. Ironically, now that we shifted to JupySQL, these decorators are not very relevant since the user interacts with JupySQL via the `%sql` magic, instead of importing and calling regular Python functions. So what I'm proposing is something simpler like this:

```python
from warnings import warn

def deprecation_warning(message):
    warn(message, FutureWarning)
    # also log the event to posthog
```

Later, we can decide if we also add posthog calls to the `@deprecated` decorators, but for now, we don't have to.
