### ISSUE TITLE
Add more error types in modify_exceptions

### ISSUE THREAD

**Issue by neelasha23** [ploomber/core#58]
The `modify_exceptions` decorator accepts TypeError and ValueError only.
https://github.com/ploomber/core/blob/1ece1158a38cac02e4f126c07d70bbcb4ea39338/src/ploomber_core/exceptions.py#L96

Many of the JupySQL errors are of different types , like SQLAlchemy ProgrammingError, OperationalError , etc. Decorating functions with `modify_exceptions` is not working in these cases.

Should we add these more specific error types ?

**Comment by edublancas** [comment]
We encountered this same problem recently. I released 0.2.10 with a fix, you can now catch the exception, add `modify_exception` and it should work, see the second example here: https://ploomber-core.readthedocs.io/en/latest/exceptions.html#catching-generic-exceptions
