### ISSUE TITLE
Inconsistent optional dependencies package name check and suggestions

### ISSUE THREAD

**Issue by yafimvo** [ploomber/core#60]
If a function has optional dependencies, we can use the `@requires` decorator. Alternatively, we might use the `check_installed` function.

However, if the package name includes "-", it will act differently.

Example:

Using requires

```
from ploomber_core.dependencies import requires

@requires(["jupysql-plugin"])
def some_optional_functionality():
    pass

some_optional_functionality()
```

this will throw the following error:

```
ModuleNotFoundError: 'jupysql_plugin' is required to use 'some_optional_functionality'. Install with: pip install 'jupysql_plugin'
```

Using check_installed

```
from ploomber_core.dependencies import check_installed

check_installed(["jupysql-plugin"], "jupysql-plugin")
```

This will not throw any errors.

To make `check_installed` work the same, we need to:

```
check_installed(["jupysql_plugin"], "jupysql-plugin")
```

1. From the [docs](https://ploomber-core.readthedocs.io/en/latest/dependencies.html#check-installed), it looks like these functions should act pretty much the same. 
2. The error thrown by `requires` might be confusing because the user typed "jupysql-plugin," while the error implies that "jupysql_plugin" is not installed and suggests running "jupysql_plugin" instead.

cc: @edublancas @idomic

**Comment by edublancas** [comment]
thanks for spotting this.

to check if a package is installed or not, we need to convert hyphens to underscores (that's why requires is showing `jupysql_plugin`), so we're missing that in check_installed

> The error thrown by requires might be confusing because the user typed "jupysql-plugin," while the error implies that "jupysql_plugin" is not installed and suggests running "jupysql_plugin" instead.

that's fine, both `pip install jupysql_plugin` and `pip install jupysql-plugin` install the same thing, pip treats both the same

let me fix `check_installed`
