### ISSUE TITLE
Hide PostHug API Key

### ISSUE THREAD

**Issue by tonykploomber** [ploomber/core#62]
I am not sure if we are using following PostHug API Key:

https://github.com/ploomber/core/blob/ed34d76898ca792c9ba8cfc691b7c1b078b13d80/src/ploomber_core/telemetry/telemetry.py#L476

If yes, we should set that as environment variable and protected by GitHub variable secrets

**Comment by edublancas** [comment]
yes we are. but this is part of the library and has to be shipped in the package. the API key won't expose any sensitive data so we're fine.

we could remove it from the repository and then inject it when uploading the package to PyPI but it'll still be visible there, I think we can keep it as is for now.
