### ISSUE TITLE
better validation when checking version updates

### ISSUE THREAD

**Issue by edublancas** [ploomber/core#66]
we're not performing version validation when checking version updates: https://github.com/ploomber/core/blob/f81a4ce8f4d8b9e3dbc1b5a4a630ddc072ad884c/src/ploomber_core/telemetry/telemetry.py#L382

this causes the "new version available" message to appear when running development versions

@anupam-tiwari: can you post the screenshot here?

**Comment by anupam-tiwari** [comment]
Here is the screenshot for reference
<img width="825" alt="Screenshot 2023-06-07 at 4 16 10 PM" src="https://github.com/ploomber/core/assets/40127722/4f2f7b3d-465c-4c02-90d7-68d31f9a2e48">

**Comment by anupam-tiwari** [comment]
Can this be the way? The only drawback is we won't be displaying this warning in dev mode, I tried to solve this error using math, the only issue is these versions are in strings and if we try to extract numbers 0.7.8 is not a valid float so the math will fail, let me know your thoughts 

```
if 'dev' in version: 
        return 
```

**Comment by edublancas** [comment]
yeah, I think your solution makes sense. we don't want to show this message if we're running a development version
