### ISSUE TITLE
improving performance

### ISSUE THREAD

**Issue by edublancas** [ploomber/core#72]
the telemetry module has many calls made every time we submit a telemetry event; however, most of them won't change from one call to the other. instead, we should call them once, and just re-submit the values again to make it more performant.

**Comment by DanielOX** [comment]
I can take up this issue but can you please add more info? what type of requests? which endpoint? which function should we primarily look into?

**Comment by edublancas** [comment]
fixed by https://github.com/ploomber/core/commit/bf83ec4d825090db85aa509bd2c4ac36875abb5c
