### ISSUE TITLE
telemetry causing performance issues

### ISSUE THREAD

**Issue by edublancas** [ploomber/core#73]
From a user on Slack:

>  have a Jupyter notebook that was using ipython-sql, sqlalchemy 1.4 and oracledb. I upgraded sqlalchemy to 2.x and I installed jupysql. The notebook is now extremely slow. A select from dual takes more than 20 seconds. What could be the problem? I am on VPN so I suspected that maybe a library is performing a network request and timing out. I defined the https_proxy in my shell; that made no difference.

> In the slow notebook: 44s to create the connection. 21s to perform a query from dual

We need to ensure that the telemetry times out quickly and if it cannot communicate with the server, it should not attempt to do so again.

**Comment by edublancas** [comment]
Update: I ran some tests on my laptop. I blocked posthog.com using littlesnitch and I couldn't reproduce the problem. The user's feedback suggested that our telemetry calls were taking too much time to time out but that wasn't my experience.

So we have to dig deeper into this. I actually didn't check what endpoint the posthog python library is hitting (so perhaps the domain isn't posthog.com?)

**Comment by yafimvo** [comment]
@edublancas Did you run anything specific? I ran some local tests on Windows and it works fine. Maybe it's something with the internet connectivity?

> So we have to dig deeper into this. I actually didn't check what endpoint the posthog python library is hitting (so perhaps the domain isn't posthog.com?)

I used [mitmproxy](https://mitmproxy.org/) and it's `app.posthog.com`. Also, I don't think that our telemetry calls should affect the query execution.

thoughts?

**Comment by edublancas** [comment]
did you block app.posthog.com with mitmproxy and found no issues?

---

If blocking isn't the problem it might be that some enterprise VPNs are throttling the connection?

**Comment by edublancas** [comment]
yeah so looks like we're unable to reproduce the issue. I'll close it
