### ISSUE TITLE
testing

### ISSUE THREAD

**Issue by edublancas** [ploomber/core#76]
in https://github.com/ploomber/core/pull/75 I introduced a change to reduce latency when capturing telemetry calls. we had a function that would check internet access by hitting google.com, if it failed, it didn't perform the telemetry call to posthog.

turns out, this was severely affecting performance so I tested what would happen if I removed the call and just make the posthog call regardless of internet status. turns out, nothing happens (calls to posthog don't break if there is no internet connection) 

@neelasha23 just to double check, can you perform some testing? try calling the telemetry ([log_api](https://github.com/ploomber/core/blob/f6611dbd02d003a9b3cfe970e4b7591736e9ddc2/src/ploomber_core/telemetry/telemetry.py#L382)) module without internet connection and let me know if you find anything weird

ensure you set the [debug flag](https://ploomber-core.readthedocs.io/en/latest/telemetry.html) so the testing events go to the debugging posthog project

**Comment by neelasha23** [comment]
Sure, working on this now!

**Comment by neelasha23** [comment]
I tired some calls `telemetry.log_api(...)` with internet on/off multiple times. The calls would have `issue_76` mentioned in the action/ metadata. I didn't get any errors. But I dont see any posthog files for 15.8. How to verify ? @edublancas

**Comment by neelasha23** [comment]
shouldn't I be able to access the posthog logs of the calls made by running the posthog-analysis.ipynb file?
